In [7]:
import pandas as pd

datos=pd.read_csv('../datos/goleadores.csv')

In [12]:
datos

,Player,Team,Country,Team Nationality,Goals,Penalty Goals,Team Total Goals
0,Germán Cano,Fluminense RJ,Argentina,Brasil,13,0,24
1,Paulinho,Atlético Mineiro,Brasil,Brasil,7,0,14
2,Dorlan Pabón,Atlético Nacional,Colombia,Colombia,6,2,12
3,Alan Patrick,Internacional,Brasil,Brasil,5,1,19
4,Artur,Palmeiras,Brasil,Brasil,5,0,22
...,...,...,...,...,...,...,...
227,Yoshimar Yotún,Sporting Cristal,Perú,Perú,1,0,14
228,Diego Zabala,Nacional,Uruguay,Uruguay,1,0,11
229,Facundo Zabala,Club Olimpia,Argentina,Paraguay,1,0,17
230,Cristián Zapata,Atlético Nacional,Colombia,Colombia,1,0,12
231,Yorman Zapata,CD Magallanes,Colombia,Chile,1,0,7

In [ ]:
def goles(equipo):
    equipo = pd.Series([equipo]).str.capitalize()[0]
    total_goles = datos.loc[datos['Team'] == equipo, 'Goals'].sum()
    return total_goles

0

In [31]:
print(goles('millonarios'))

4

In [32]:
print(goles('Internacional'))

19

In [40]:
def jugadores_info(nombre):
    """
    Devuelve la información de los jugadores.
    """
    datos['Player'] = datos['Player'].str.lower()  # Normalizar nombres de jugadores a minúsculas
    nombre = nombre.lower()  # Normalizar el nombre del jugador a minúsculas
    df_player = datos[datos['Player'] == nombre]
    return df_player.to_dict(orient='records')

In [35]:
def goleadores(opcion):
    """
    Devuelve los goleadores de la liga.
    """
    if opcion == 'top_10':
        gol_10= datos['Goals'].iloc[10]
        return datos[datos['Goals'] >= gol_10]
    elif opcion == 'top_5':
        gol_5= datos['Goals'].iloc[5]
        return datos[datos['Goals'] >= gol_5]
    elif opcion == 'top_3':
        gol_3= datos['Goals'].iloc[3]
        return datos[datos['Goals'] >= gol_3]
    elif opcion == 'top_1':
        gol_1= datos['Goals'].iloc[1]
        return datos[datos['Goals'] >= gol_1]
    else:
        return "Opción no válida. Por favor, elige entre 'top_10', 'top_5', 'top_3' o 'top_1'."

goleadores('top_10')  # Ejemplo de uso

,Player,Team,Country,Team Nationality,Goals,Penalty Goals,Team Total Goals
0,Germán Cano,Fluminense RJ,Argentina,Brasil,13,0,24
1,Paulinho,Atlético Mineiro,Brasil,Brasil,7,0,14
2,Dorlan Pabón,Atlético Nacional,Colombia,Colombia,6,2,12
3,Alan Patrick,Internacional,Brasil,Brasil,5,1,19
4,Artur,Palmeiras,Brasil,Brasil,5,0,22
5,Luciano Pons,Independiente Medellín,Argentina,Colombia,5,0,16
6,Luis Advíncula,Boca Juniors,Perú,Argentina,4,0,13
7,Rubén Bentancourt,Liverpool,Uruguay,Uruguay,4,1,4
8,Ronnie Fernández,Bolívar,Chile,Bolivia,4,0,13
9,John Kennedy,Fluminense RJ,Brasil,Brasil,4,0,24
10,Guillermo Paiva,Club Olimpia,Paraguay,Paraguay,4,0,17
11,Enrique Triverio,The Strongest,Argentina,Bolivia,4,1,5
12,Enner Valencia,Internacional,Ecuador,Brasil,4,0,19
13,Vítor Roque,Athletico Paranaense,Brasil,Brasil,4,0,12

In [38]:
#####INICIO DE LA CREACIÓN DE API

from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd

# Crear la instancia de FastAPI
app = FastAPI()

# Cargar los datos
df = pd.read_csv('../datos/goleadores.csv')

# Modelo de Pydantic para la validación de datos
class Player(BaseModel):
    name: str
    team: str
    country: str
    team_nationality: str
    goals: int
    penalty_goals: int

In [41]:
jugadores_info('Paulinho')

[{'Player': 'paulinho',
  'Team': 'Atlético Mineiro',
  'Country': 'Brasil',
  'Team Nationality': 'Brasil',
  'Goals': 7,
  'Penalty Goals': 0,
  'Team Total Goals': 14}]